[package]
name = "orbit-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.orbit]
stability = "experimental"

[lints]
workspace = true

[features]
default = []

[dependencies]
chrono.workspace = true
hostname.workspace = true
orbit-common = { path = "../orbit-common" }
orbit-store = { path = "../orbit-store" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
