[package]
name = "orbit-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.orbit]
stability = "experimental"

[lints]
workspace = true

[features]
default = []

[dependencies]
orbit-common = { path = "../orbit-common" }
orbit-registry = { path = "../orbit-registry" }
orbit-tools = { path = "../orbit-tools" }
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
chrono.workspace = true
tempfile.workspace = true
toml.workspace = true
